image: node:latest

cache:
  paths: 
    - node_modules/

build:
  stage: build
  script:
    - npm install --global yarn
    - yarn
    - yarn run build
  artifacts:
    paths:
      - build

unit:
  stage: test
  script:
    - npm install --global yarn
    - yarn
    - yarn run build-css
    - yarn run test

pages:
  stage: deploy
  script:
    - npm install --global yarn
    - yarn
    - yarn run build
    - cp -r build public
  artifacts:
    paths:
      - public
  only:
    - master