export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_QUOTES_SUCCESS = 'LOAD_QUOTES_SUCCESS';
export const LOAD_SOCIAL_SUCCESS = 'LOAD_SOCIAL_SUCCESS';
export const LOAD_STATS_SUCCESS = 'LOAD_STATS_SUCCESS';

export const LOAD_PROJECTS_FAILURE = 'LOAD_PROJECTS_FAILURE';
export const LOAD_QUOTES_FAILURE = 'LOAD_QUOTES_FAILURE';
export const LOAD_SOCIAL_FAILURE = 'LOAD_SOCIAL_FAILURE';
export const LOAD_STATS_FAILURE = 'LOAD_STATS_FAILURE';